### PR TITLE
Unit filters

### PR DESCRIPTION
**Pull request by cwibach**
Filters by price, # of bedrooms, # of bathrooms with some refactoring done to separate components

### CODE REVIEW

**Comment by owen-sellner** [comment]
Could you include a screenshot in the pull request?

**Comment by cwibach** [comment]
image

Here's the image of what it looks like

**Review by owen-sellner — DISMISSED** [review]
1) For the bedrooms and bathrooms if the minimum is greater than the maximum no alert is sent.

2) Would it be possible to return a no-results message if all the postings are filtered out? Cause right now it just shows an empty page.

image

**Comment by cwibach** [comment]
Sure I can do that. Can you merge it so I can continue coding?

**Review by HoEddie — APPROVED** [review]
Looks good!

**Pull request merged**
